twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
knp_paginator:
    template:
        pagination: 'others/twitter_bootstrap_v4_pagination.html.twig'
